substitutions:
  name: "current-sensor"
  friendly_name: Capteur De Courant

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

logger:
  hardware_uart: UART0
  level: DEBUG
  logs:
    sensor: DEBUG
    ads1115: DEBUG
    ct_clamp: DEBUG

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
    - ssid: !secret wifi_ssid3
      password: !secret wifi_password3    
    - ssid: !secret wifi_ssid4
      password: !secret wifi_password4


debug:
  update_interval: 5s


  

# Activer l'accès à l'API Home Assistant
api:

ota:


time:
  - platform: homeassistant
    id: homeassistant_time
# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"



binary_sensor:
  - platform: homeassistant
    id: heures_creuses
    entity_id: schedule.heures_creuses
    internal : true

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

ads1115:
  - address: 0x48
    continuous_mode: true


# Sensors with general information.
sensor:
  - platform: debug
    free:
      name: "Heap Free"

  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 60s


  - platform: ads1115
    multiplexer: "A1_GND"
    gain: 2.048
    name: "ADS1115 Channel A1-GND"
    id: ads_2
    update_interval: 1s
    accuracy_decimals: 10


  - platform: ads1115
    multiplexer: "A3_GND"
    gain: 2.048
    name: "ADS1115 Channel A3-GND"
    id: ads_4
    update_interval: 1s

 
  ## 15 amp clamp 
  - platform: ct_clamp
    sensor: ads_2
    name: ${name} 2
    update_interval: 2s    
    accuracy_decimals: 10
    filters:
      #- multiply: 1000
      - calibrate_polynomial:
          degree: 4
          datapoints:
            - 0 -> 0
            - 0.0006 -> 0
            - 0.0214732761383 -> 3.4
            - 0.0318451480865 -> 5
            - 0.0525032920837 -> 8.2
          

  ## 100 amp clamp 
  - platform: ct_clamp
    sensor: ads_4
    id: amperes_sensor_4
    name: ${name} 4
    update_interval: 2s
    accuracy_decimals: 10
    filters:
      #- multiply: 1000
      - calibrate_linear :
        - 0 -> 0        
        - 0.0165476207733 -> 4.687065
        - 0.0229258308411 -> 6.423819

  - platform: template
    name: "Instant Power ${name} 4"
    id: power_sensor_4
    unit_of_measurement: 'W'
    accuracy_decimals: 2
    # Calcul de la puissance instantanée
    lambda: |-
      return id(amperes_sensor_4).state * 230.0; 

  - platform: template
    name: "Puissance Instantanee HC ${name}"
    id: PW_HC
    unit_of_measurement: 'W'
    accuracy_decimals: 2
    # Calcul de la puissance instantanée
    lambda: |-
      if (id(heures_creuses).state) {
        return id(amperes_sensor_4).state * 230.0;
      } else {
        return 0.0;
      }

  - platform: template
    name: "Puissance Instantanee HP ${name}"
    id: PW_HP
    unit_of_measurement: 'W'
    accuracy_decimals: 2
    # Calcul de la puissance instantanée 
    lambda: |-
      if (id(heures_creuses).state) {
        return 0.0;
      } else {
        return id(amperes_sensor_4).state * 230.0;
      }



  - platform: total_daily_energy
    name: "Daily Energy Consumption ${name} 4"
    power_id: power_sensor_4
    unit_of_measurement: kWh
    accuracy_decimals: 2
    method: trapezoid
    filters:
      - multiply: 0.001 # Convertir W en kW


  - platform: total_daily_energy
    name: "Compteur Jour Heure Creuses"
    power_id: PW_HC
    unit_of_measurement: kWh
    accuracy_decimals: 2
    method: trapezoid
    filters:
      - multiply: 0.001 # Convertir W en kW

  - platform: total_daily_energy
    name: "Compteur Jour Heure Pleine"
    power_id: PW_HP
    unit_of_measurement: kWh
    accuracy_decimals: 2
    method: trapezoid
    filters:
      - multiply: 0.001 # Convertir W en kW

